name: CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    services:
      mysql:
        image: mysql:5.7
        ports:
          - 3306:3306
        env:
          MYSQL_ALLOW_EMPTY_PASSWORD: "yes"

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Set up Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '16'

    - name: Install dependencies
      run: npm install

    - name: Set up PHP
      uses: shivammathur/setup-php@v2
      with:
        php-version: '8.1'
        extensions: mbstring, pdo, pdo_mysql

    - name: Install Composer dependencies
      run: composer install

    - name: Copy .env example
      run: cp .env.example .env

    - name: Update environment variables
      run: |
        echo "DB_CONNECTION=mysql" >> .env
        echo "DB_HOST=127.0.0.1" >> .env
        echo "DB_PORT=3306" >> .env
        echo "DB_DATABASE=fullstack_assessment_db" >> .env
        echo "DB_USERNAME=root" >> .env
        echo "DB_PASSWORD=" >> .env  # No password

    - name: Wait for MySQL to be ready and create database
      run: |
        sudo apt-get install -y mysql-client
        # Wait for MySQL to be available
        for i in {30..0}; do
          if mysql -h127.0.0.1 -uroot -e 'select 1'; then
            break
          fi
          echo 'MySQL init process in progress...'
          sleep 1
        done
        echo 'MySQL is up - creating database'
        # Create the database
        mysql -h 127.0.0.1 -u root -e "CREATE DATABASE IF NOT EXISTS fullstack_assessment_db;"
        # Ensure the database exists
        mysql -h 127.0.0.1 -u root -e "SHOW DATABASES;"

    - name: Generate application key
      run: php artisan key:generate

    - name: Run migrations
      run: php artisan migrate

    - name: Seed database
      run: php artisan db:seed

    - name: Run tests
      run: php artisan test
